version: '3'
services:
  python:
    container_name: python
    build: 
    # The build context is the set of files that your build can access. 
      # set of files that your build can access. 
      # Details can be found https://docs.docker.com/build/building/context/#what-is-a-build-context
      context: ./ 
      dockerfile: docker/python/Dockerfile
    env_file: .env
    # depends_on expresses startup and shutdown dependencies between services.
    # The depends_on is to make sure postgres is run first before running dbt
    volumes:
      - ./:/data-engineering/
    depends_on:
      postgres_udacity:
        condition: service_healthy

  postgres_udacity:
    container_name: postgres
    # build dockerfile for postgres
    build: docker/postgres/
    restart: always
    hostname: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_udacity:/var/lib/postgresql/data
    # update the default port to the new port
    # without it, it will still listen to the default port 5432
    command: postgres -c port=${POSTGRES_PORT} 
    # Set up postgres database 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres  -p ${POSTGRES_PORT}"]
      interval: 1s
      timeout: 5s
      retries: 10

  cassandra_seed:
    image: cassandra:3.11
    restart: "no"
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    container_name: cassandra-seed
    # networks:
    #   - cassandra_seed
    expose:
      - "7000"
    ports:
      - target: 9042
        published: 9042
        protocol: tcp
        mode: host
    volumes:
      - cassandra_seed:/var/lib/cassandra/data
    environment:
      CASSANDRA_BROADCAST_ADDRESS: "cassandra-seed"
      CASSANDRA_NUM_TOKENS: 4
      CASSANDRA_START_RPC: true

  # cassandra_node:
  #   image: cassandra:3.11
  #   restart: "no"
  #   logging:
  #     options:
  #       max-size: "5m"
  #       max-file: "1"
  #   container_name: cassandra-node
  #   hostname: cassandra-node
  #   # networks:
  #   #   - cassandra
  #   expose:
  #     - "7000"
  #   ports:
  #     - target: 9042
  #       published: 9043
  #       protocol: tcp
  #       mode: host
  #   volumes:
  #     - cassandra_node:/var/lib/cassandra/data
  #   environment:
  #     CASSANDRA_SEEDS: "cassandra-seed"
  #     CASSANDRA_LISTEN_ADDRESS: cassandra-node
  #     CASSANDRA_BROADCAST_ADDRESS: cassandra-node
  #     CASSANDRA_START_RPC: true
  #     # CASSANDRA_ENDPOINT_SNITCH: SimpleSnitch
  #     CASSANDRA_NUM_TOKENS: 4
  #     # CASSANDRA_CLUSTER_NAME: cluster
  #     # CASSANDRA_DC: dc
  #     # HEAP_NEWSIZE: 32M
  #     # MAX_HEAP_SIZE: 4M

volumes:
  postgres_udacity:
  cassandra_seed:
  # cassandra_node: